mod personal_info_1;
mod personal_info_2;
mod personal_info_3;
mod personal_info_4;
mod personal_info_5_b2w2;
mod personal_info_5_bw;
mod personal_info_6_ao;
mod personal_info_6_xy;
mod personal_info_7;
mod personal_info_7_gg;
mod personal_info_8_bdsp;
mod personal_info_8_la;
mod personal_info_8_swsh;
mod personal_info_9_sv;

pub use personal_info_1::*;
pub use personal_info_2::*;
pub use personal_info_3::*;
pub use personal_info_4::*;
pub use personal_info_5_b2w2::*;
pub use personal_info_5_bw::*;
pub use personal_info_6_ao::*;
pub use personal_info_6_xy::*;
pub use personal_info_7::*;
pub use personal_info_7_gg::*;
pub use personal_info_8_bdsp::*;
pub use personal_info_8_la::*;
pub use personal_info_8_swsh::*;
pub use personal_info_9_sv::*;
