#[derive(PartialEq, Copy, Clone)]
#[repr(u8)]
pub enum GameVersion {
    // The following values are IDs stored within PKM data, and can also identify individual games.
    Unknown = 0,
    S = 1,
    R = 2,
    E = 3,
    FR = 4,
    LG = 5,
    CXD = 15,
    D = 10,
    P = 11,
    Pt = 12,
    HG = 7,
    SS = 8,
    W = 20,
    B = 21,
    W2 = 22,
    B2 = 23,
    X = 24,
    Y = 25,
    AS = 26,
    OR = 27,
    SN = 30,
    MN = 31,
    US = 32,
    UM = 33,
    GO = 34,
    RD = 35,
    GN = 36,
    BU = 37,
    YW = 38,
    GD = 39,
    SI = 40,
    C = 41,
    GP = 42,
    GE = 43,
    SW = 44,
    SH = 45,
    PLA = 47,
    BD = 48,
    SP = 49,
    RB,
    RBY,
    GS,
    GSC,
    RS,
    RSE,
    FRLG,
    RSBOX,
    COLO,
    XD,
    DP,
    DPPt,
    HGSS,
    BATREV,
    BW,
    B2W2,
    XY,
    ORASDEMO,
    ORAS,
    SM,
    USUM,
    GG,
    SWSH,
    BDSP,
    Gen1,
    Gen2,
    Gen3,
    Gen4,
    Gen5,
    Gen6,
    Gen7,
    Gen7b,
    Gen8,
    StadiumJ,
    Stadium,
    Stadium2,
    Any,
}

impl From<usize> for GameVersion {
    fn from(var: usize) -> Self {
        match var {
            1 => GameVersion::S,
            2 => GameVersion::R,
            3 => GameVersion::E,
            4 => GameVersion::FR,
            5 => GameVersion::LG,
            15 => GameVersion::CXD,
            10 => GameVersion::D,
            11 => GameVersion::P,
            12 => GameVersion::Pt,
            7 => GameVersion::HG,
            8 => GameVersion::SS,
            20 => GameVersion::W,
            21 => GameVersion::B,
            22 => GameVersion::W2,
            23 => GameVersion::B2,
            24 => GameVersion::X,
            25 => GameVersion::Y,
            26 => GameVersion::AS,
            27 => GameVersion::OR,
            30 => GameVersion::SN,
            31 => GameVersion::MN,
            32 => GameVersion::US,
            33 => GameVersion::UM,
            34 => GameVersion::GO,
            35 => GameVersion::RD,
            36 => GameVersion::GN,
            37 => GameVersion::BU,
            38 => GameVersion::YW,
            39 => GameVersion::GD,
            40 => GameVersion::SI,
            41 => GameVersion::C,
            42 => GameVersion::GP,
            43 => GameVersion::GE,
            44 => GameVersion::SW,
            45 => GameVersion::SH,
            47 => GameVersion::PLA,
            48 => GameVersion::BD,
            49 => GameVersion::SP,
            50 => GameVersion::RB,
            51 => GameVersion::RBY,
            52 => GameVersion::GS,
            53 => GameVersion::GSC,
            54 => GameVersion::RS,
            55 => GameVersion::RSE,
            56 => GameVersion::FRLG,
            57 => GameVersion::RSBOX,
            58 => GameVersion::COLO,
            59 => GameVersion::XD,
            60 => GameVersion::DP,
            61 => GameVersion::DPPt,
            62 => GameVersion::HGSS,
            63 => GameVersion::BATREV,
            64 => GameVersion::BW,
            65 => GameVersion::B2W2,
            66 => GameVersion::XY,
            67 => GameVersion::ORASDEMO,
            68 => GameVersion::ORAS,
            69 => GameVersion::SM,
            70 => GameVersion::USUM,
            71 => GameVersion::GG,
            72 => GameVersion::SWSH,
            73 => GameVersion::BDSP,
            74 => GameVersion::Gen1,
            75 => GameVersion::Gen2,
            76 => GameVersion::Gen3,
            77 => GameVersion::Gen4,
            78 => GameVersion::Gen5,
            79 => GameVersion::Gen6,
            80 => GameVersion::Gen7,
            81 => GameVersion::Gen7b,
            82 => GameVersion::Gen8,
            83 => GameVersion::StadiumJ,
            84 => GameVersion::Stadium,
            85 => GameVersion::Stadium2,
            86 => GameVersion::Any,
            _ => GameVersion::Unknown,
        }
    }
}
