pub enum RibbonG5 {
    ChampionSinnoh = 0,
    Ability,
    AbilityGreat,
    AbilityDouble,
    AbilityMulti,
    AbilityPair,
    AbilityWorld,
    Alert,
    Shock = 0x10,
    Downcast,
    Careless,
    Relax,
    Snooze,
    Smile,
    Gorgeous,
    Royal,
    GorgeousRoyal = 0x20,
    Footprint,
    Record,
    Event,
    Legend,
    ChampionWorld,
    Birthday,
    Special,
    Souvenir = 0x30,
    Wishing,
    Classic,
    Premier,
    G3Cool = 0x100,
    G3CoolSuper,
    G3CoolHyper,
    G3CoolMaster,
    G3Beauty,
    G3BeautySuper,
    G3BeautyHyper,
    G3BeautyMaster,
    G3Cute = 0x110,
    G3CuteSuper,
    G3CuteHyper,
    G3CuteMaster,
    G3Smart,
    G3SmartSuper,
    G3SmartHyper,
    G3SmartMaster,
    G3Tough = 0x120,
    G3ToughSuper,
    G3ToughHyper,
    G3ToughMaster,
    ChampionG3,
    Winning,
    Victory,
    Artist,
    Effort = 0x130,
    ChampionBattle,
    ChampionRegional,
    ChampionNational,
    Country,
    National,
    Earth,
    World,
    G4Cool = 0x200,
    G4CoolGreat,
    G4CoolUltra,
    G4CoolMaster,
    G4Beauty,
    G4BeautyGreat,
    G4BeautyUltra,
    G4BeautyMaster,
    G4Cute = 0x210,
    G4CuteGreat,
    G4CuteUltra,
    G4CuteMaster,
    G4CSmart,
    G4SmartGreat,
    G4SmartUltra,
    G4SmartMaster,
    G4Tough = 0x220,
    G4ToughGreat,
    G4ToughUltra,
    G4ToughMaster,
}
