#[repr(u16)]
pub enum RibbonG7 {
    ChampionKalos = 0,
    ChampionG3,
    ChampionSinnoh,
    BestFriends,
    Training,
    BattlerSkillful,
    BattlerExpert,
    Effort,
    Alert = 0x10,
    Shock,
    Downcast,
    Careless,
    Relax,
    Snooze,
    Smile,
    Gorgeous,
    Royal = 0x20,
    GorgeousRoyal,
    Artist,
    Footprint,
    Record,
    Legend,
    Country,
    National,
    Earth = 0x30,
    World,
    Classic,
    Premier,
    Event,
    Birthday,
    Special,
    Souvenir,
    Wishing = 0x100,
    ChampionBattle,
    ChampionRegional,
    ChampionNational,
    ChampionWorld,
    ChampionG6Hoenn = 0x107,
    ContestStar = 0x110,
    MasterCoolness,
    MasterBeauty,
    MasterCuteness,
    MasterToughness,
    ChampionAlola,
    BattleRoyale,
    BattleTreeGreat = 0x120,
    BattleTreeMaster
}
