use crate::Move;

pub const MAX_SPECIES_ID_8A: usize = 905;

pub const MOVE_SHOP_8_LA: [usize; 61] = [
    Move::FalseSwipe as usize,
    Move::FireFang as usize,
    Move::ThunderFang as usize,
    Move::IceFang as usize,
    Move::IceBall as usize,
    Move::RockSmash as usize,
    Move::Spikes as usize,
    Move::Bulldoze as usize,
    Move::AerialAce as usize,
    Move::StealthRock as usize,
    Move::Swift as usize,
    Move::TriAttack as usize,
    Move::MagicalLeaf as usize,
    Move::OminousWind as usize,
    Move::PowerShift as usize,
    Move::FocusEnergy as usize,
    Move::BulkUp as usize,
    Move::CalmMind as usize,
    Move::Rest as usize,
    Move::BabyDollEyes as usize,
    Move::FirePunch as usize,
    Move::ThunderPunch as usize,
    Move::IcePunch as usize,
    Move::DrainPunch as usize,
    Move::PoisonJab as usize,
    Move::PsychoCut as usize,
    Move::ZenHeadbutt as usize,
    Move::LeechLife as usize,
    Move::XScissor as usize,
    Move::RockSlide as usize,
    Move::ShadowClaw as usize,
    Move::IronHead as usize,
    Move::IronTail as usize,
    Move::MysticalFire as usize,
    Move::WaterPulse as usize,
    Move::ChargeBeam as usize,
    Move::EnergyBall as usize,
    Move::IcyWind as usize,
    Move::SludgeBomb as usize,
    Move::EarthPower as usize,
    Move::ShadowBall as usize,
    Move::Snarl as usize,
    Move::FlashCannon as usize,
    Move::DazzlingGleam as usize,
    Move::GigaImpact as usize,
    Move::AquaTail as usize,
    Move::WildCharge as usize,
    Move::HighHorsepower as usize,
    Move::Megahorn as usize,
    Move::StoneEdge as usize,
    Move::Outrage as usize,
    Move::PlayRough as usize,
    Move::HyperBeam as usize,
    Move::Flamethrower as usize,
    Move::Thunderbolt as usize,
    Move::IceBeam as usize,
    Move::Psychic as usize,
    Move::DarkPulse as usize,
    Move::DracoMeteor as usize,
    Move::SteelBeam as usize,
    Move::VoltTackle as usize,
];
