mod personal_table_1;
mod personal_table_2;
mod personal_table_3;
mod personal_table_4;
mod personal_table_5_b2w2;
mod personal_table_5_bw;
mod personal_table_6_ao;
mod personal_table_6_xy;
mod personal_table_7;
mod personal_table_7_gg;
mod personal_table_8_bdsp;
mod personal_table_8_la;
mod personal_table_8_swsh;

pub use personal_table_1::*;
pub use personal_table_2::*;
pub use personal_table_3::*;
pub use personal_table_4::*;
pub use personal_table_5_b2w2::*;
pub use personal_table_5_bw::*;
pub use personal_table_6_ao::*;
pub use personal_table_6_xy::*;
pub use personal_table_7::*;
pub use personal_table_7_gg::*;
pub use personal_table_8_bdsp::*;
pub use personal_table_8_la::*;
pub use personal_table_8_swsh::*;
