mod ribbon_index;
mod ribbon_set_affixed;
mod ribbon_set_common_3;
mod ribbon_set_common_4;
mod ribbon_set_common_6;
mod ribbon_set_common_7;
mod ribbon_set_common_8;
mod ribbon_set_event_3;
mod ribbon_set_event_4;
mod ribbon_set_mark_8;

pub use ribbon_index::*;
pub use ribbon_set_affixed::*;
pub use ribbon_set_common_3::*;
pub use ribbon_set_common_4::*;
pub use ribbon_set_common_6::*;
pub use ribbon_set_common_7::*;
pub use ribbon_set_common_8::*;
pub use ribbon_set_event_3::*;
pub use ribbon_set_event_4::*;
pub use ribbon_set_mark_8::*;
